version: "3.8"
name: remove-product-background
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    stdin_open: true
    env_file:
      - /.env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    ports:
      - "3001:3001"

    volumes:
      - ./:/app # sync files from host to container
      # followings are needed to not share node_modules from host to container. You are specifying the directories that shouldn't be reloaded in the container
      - /app/frontend/node_modules
      - /app/backend/node_modules

volumes:
  postgres-data:
