version: "3.8"
name: shopify-app
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  express:
    stdin_open: true
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend # sync files between host and container. Enable hot reloading
      - /backend/node_modules/ # do not share node_modules between host and container
  vite:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
      - "64999:64999"
    volumes:
      - ./frontend:/frontend # sync files between host and container. Enable hot reloading
      - /frontend/node_modules/ # do not share node_modules between host and container

volumes:
  postgres-data:
